
####!//!fiscall
GET  http://localhost:8484/api/fiscal/query?page=1&limit=10&withdrawal=true&forTeacher=false&byWallet=false&userId=60acaaf7f8d9ce2934b0776a&classId=60dffd63ec031403c04893a1 HTTP/1.1


###

####!//!fiscallt
patch  http://localhost:8484/api/fiscal/checkout/60acaaf7f8d9ce2934b0776a HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGM0OWEzOTg4NjMyMDI2ZjAwNzU3YTkiLCJlbWFpbCI6Iml0YWxraUBpdGFsa2kuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaXNUZWFjaGVyIjpmYWxzZSwiaWF0IjoxNjIzNDk4MDczfQ.OZRhZs-uxhAJpEVNbBuB5lImKA3FWfM6deTFVIqemvw

{
  "payment": 3,
  "description": "hi"
}

###
POST http://localhost:8484/api/fiscal/student/pay?calBack=http://localhost:8484/static HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MWMzNWRhZTQ4MWMxYzQ1ZGM5ZWY1NmEiLCJlbWFpbCI6IjMyMTJAbTIzMi5jb20iLCJpc0FkbWluIjpmYWxzZSwiaXNUZWFjaGVyIjpmYWxzZSwiaWF0IjoxNjQwMTkzNDkxfQ.Deovai5WVFn6hrEFXs_V3NBkIwYLIUcoYOGbrlLkgp0

{
  "amount": 80005
}

# ###
# GET http://localhost:8484/api/fiscal/student/verify?fiscalId=60d2ffa75e24752ce432bcf7&Authority=000000000000000000000000000000527770&Status=OK HTTP/1.1
# Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFjYWFmN2Y4ZDljZTI5MzRiMDc3NmEiLCJmdWxsTmFtZSI6Im1tbWRyZXphIiwiZW1haWwiOiJtQG0xLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpc1RlYWNoZXIiOnRydWUsImlhdCI6MTYyMTkyODY5NX0.Te-vXZqmdnICIbXhcRPt9mOwu2vzppOf8lXOcuij40Y

###
GET http://localhost:8484/api/fiscal/studentsFiscal/60b37406dcd0966c9c64cbc5 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFjYWFmN2Y4ZDljZTI5MzRiMDc3NmEiLCJmdWxsTmFtZSI6Im1tbWRyZXphIiwiZW1haWwiOiJtQG0xLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpc1RlYWNoZXIiOnRydWUsImlhdCI6MTYyMTkyODY5NX0.Te-vXZqmdnICIbXhcRPt9mOwu2vzppOf8lXOcuij40Y

###

PATCH http://localhost:8484/api/fiscal/return/student/612344670c01b02e0c5c5bdb?dateId=612343800c01b02e0c5c5bd8&userId=60b37406dcd0966c9c64cbc5 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGFjYWFmN2Y4ZDljZTI5MzRiMDc3NmEiLCJmdWxsTmFtZSI6Im1tbWRyZXphIiwiZW1haWwiOiJtQG0xLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpc1RlYWNoZXIiOnRydWUsImlhdCI6MTYyMTkyODY5NX0.Te-vXZqmdnICIbXhcRPt9mOwu2vzppOf8lXOcuij40Y


